title: "I'd Rather Be Writing - David CHEN"
name: "I'd Rather Be Writing"
description: Technical writing blog focusing on the latest trends, news, and other topics in the field of technical communication.
media: https://s3.us-west-1.wasabisys.com/idbwmedia.com/
host: 127.0.0.1
port: 4029
feedback_email: drchen.gw@gmail.com
sidebar_accordion: true
markdown: redcarpet
show_audience_label: true
output: web
paginate: 15
timezone: America/Los_Angeles
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

format: web
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo


url: https://davidnsw.github.io/th/


exclude:
  - _drafts
  - .idea
  - _site
  - vendor

# this enables collections
collections:
  restapicourse:
    output: true
  publishingapidocs:
    output: true
  voiceovertechniques:
    output: true
  visualcommunication:
    output: true
  podcasts:
    output: true
  youngadultnovel:
    output: true
  user_centered_doc:
    output: true
# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      author: <a href='/aboutme/'>Tom Johnson</a>
  -
    scope:
      path: ""
      type: "tooltips_demo"
    values:
      layout: "page"
      search: true
  -
    scope:
      path: ""
      type: "restapicourse"
    values:
      layout: "page_restapicourse"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "podcasts"
    values:
      layout: "itunes"

  -
    scope:
      path: ""
      type: "visualcommunication"
    values:
      layout: "page_visualcommunication"
      comments: true
      search: true

  -
    scope:
      path: ""
      type: "youngadultnovel"
    values:
      layout: "page_yanovel"

  -
    scope:
      path: ""
      type: "user_centered_doc"
    values:
      layout: "page_user_centered_doc"
      comments: true
      search: true

target: web

## itunes feed settings

podcast_url: https://davidnsw.github.io/th/
podcast_album_art: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/idratherbewritinglogo.png
podcast_title: I'd Rather Be Writing Podcast
podcast_owner: David CHEN
podcast_email: drchen.gw@gmail.com
podcast_category: Technology
podcast_explicit: "no"
podcast_author: David CHEN
podcast_description: Topics and issues for technical writers. Improve your technical communication role. Empower users with better documentation.
podcast_summary: A technical writing podcast about the latest trends and practices in the field of technical communication. Technical communication includes topics like technical writing (software help), information architecture, usability, API documentation, information design, web design, illustration, DITA, structured authoring, visual communication, and more. If you're a technical writer or interested in technical writing, this is the one of few podcasts in this niche. I also have a blog at https://idratherbewriting.com where the podcasts and other blog topics are published.
podcast_subtitle: Technical writing trends, innovations, and news. Content original from idratherbewriting.com. Hosted by Tom Johnson.


####### Algolia configuration ###########
algolia:
  application_id: XUM0ZBII9L
  index_name: idratherbewriting
  search_only_api_key: aa11df1f45809fcdfb5b7bc89a301682
  files_to_exclude:
    - ./*.html
    - redirects/*
    - files/**/*
    - pages/category-archives/*
    - pages/date-based-archives/*
  nodes_to_index: 'p,.description'
eventbrite_public_token: FUQRFCCTNLYIUXJZQCSV

####### jekyll seo tag configuration #######
title: I'd Rather Be Writing
tagline: Technical writing blog focusing on the latest trends, news, and other topics in the field of technical communication.
description: This blog covers topics in technical writing, technical communication, API documentation, and other topics.
url: https://idratherbewriting.com
author:
  twitter: davidnsw
twitter:
  username: davidnsw
  card: summary

logo: https://s3.us-west-1.wasabisys.com/idbwmedia.com/images/idratherbewriting-site-logo.png

social:
  name: David CHEN
  links:
    - https://twitter.com/davidnsw
    - https://www.facebook.com/davidnsw
    - https://www.linkedin.com/in/davidnsw/
    - https://github.com/davidnsw

facebook:
  app_id: 247143161970549
  publisher: 3968842976464

webmaster_verifications:
  google: i1qwK1LFgKEQHUtpm8o7OOOeK9i54NUQwKR4vXRqlFs
  bing: 352636FE6BAFC693A6938983FC6A227E

lang: en_US
