destination: ../docapis-pdf
url: "http://127.0.0.1:4033"
baseurl: "/docapis"
port: 4033
output: pdf
print_title: Documenting REST APIs
print_subtitle: "Tom Johnson"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true


markdown: redcarpet
print: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude:
  - _drafts
  - .idea
  - _site
  - _posts
  - pages/
  - _includes/sidebar_comics.html
  - js/customscripts.js


# this enables collections
collections:
  restapicourse:
    output: true

# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "restapicourse"
    values:
      layout: "page_print"
      comments: true
      search: true

sass:
    sass_dir: _sass

